/**
 * AI question types generated by the LLM.
 */
export type AiQuestionType = "short_answer" | "multiple_choice";

export interface AiGeneratedOption {
  text: string;
  isCorrect: boolean;
}

export interface AiGeneratedQuestion {
  questionType: AiQuestionType;
  prompt: string;
  options?: AiGeneratedOption[]; // only for multiple_choice
  answer: string; // short_answer text or correct option text for MC
  explanation: string;
}

export interface AiTestDraftInput {
  prompt: string;
  organizationName: string;
  questionCount: number;
  questionType: AiQuestionType;
  difficulty: "beginner" | "intermediate" | "advanced";
}

export interface AiTestDraftOutput {
  title: string;
  description: string;
  prompt: string;
  providerLabel: string;
  questions: AiGeneratedQuestion[];
}

// ── Legacy compat (kept so existing imports don't break) ──

export type DeterministicTestDraftInput = {
  prompt: string;
  organizationName: string;
  questionCount: number;
  questionType?: AiQuestionType;
};

export type DeterministicGeneratedQuestion = AiGeneratedQuestion;

export type DeterministicGeneratedTestDraft = AiTestDraftOutput;
